import { Container, Theme } from "@radix-ui/themes";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google"; 
import "./config-theme.css";
import NavBar from "./NavBar";
import AuthProvider from "./auth/AuthProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body className={inter.className}>
        <AuthProvider>
        <Theme accentColor="violet">
          <NavBar />
          <main className="p-5">
            <Container>{children}</Container>
            </main>
          {/* <ThemePanel/> */}
        </Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
