import { Container, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "./auth/AuthProvider";
import "./config-theme.css";
import "./globals.css";
import NavBar from "./NavBar";
import ReactQueryProvider from "./ReactQueryProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body className={inter.className}>
        <ReactQueryProvider>
          <AuthProvider>
            <Theme accentColor="jade">
              <NavBar />
              <main className="p-5">
                <Container>{children}</Container>
              </main>
              {/* <ThemePanel/> */}
            </Theme>
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
